application: eurobot-scoreboard
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /referee
  script: referee.py

- url: /.*
  script: public.py

